// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace Lib
{
    public partial class HousePriceForecast
    {
        /// <summary>
        /// model input class for HousePriceForecast.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(1)]
            [ColumnName(@"Quận")]
            public string Quận { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"Loại Hình")]
            public string Loại_Hình { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"Pháp Lý")]
            public string Pháp_Lý { get; set; }

            [LoadColumn(7)]
            [ColumnName(@"Diện tích sử dụng")]
            public float Diện_tích_sử_dụng { get; set; }

            [LoadColumn(8)]
            [ColumnName(@"Giá thị trường")]
            public float Giá_thị_trường { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for HousePriceForecast.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"Quận")]
            public float[] Quận { get; set; }

            [ColumnName(@"Loại Hình")]
            public float[] Loại_Hình { get; set; }

            [ColumnName(@"Pháp Lý")]
            public float[] Pháp_Lý { get; set; }

            [ColumnName(@"Diện tích sử dụng")]
            public float Diện_tích_sử_dụng { get; set; }

            [ColumnName(@"Giá thị trường")]
            public float Giá_thị_trường { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("HousePriceForecast.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

    }
}
